# Generated by Django 5.0.6 on 2024-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('national', 'National'), ('international', 'International'), ('science_technology', 'Science & Technology'), ('entertainment', 'Entertainment'), ('business', 'Business')], max_length=50),
        ),
    ]
